name: bmi_calculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^10.1.0
  http: ^0.13.5
  dart_json_mapper:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8


flutter:
  uses-material-design: true
